auth:
  registry.hub.docker.com:
    username: USERNAME
    password: PASSWORD
images:
  gcr.io/kaniko-project/executor:debug,latest: alterem/kaniko-executor
  k8s.gcr.io/sig-storage/csi-attacher: alterem/csi-attacher
  k8s.gcr.io/sig-storage/csi-provisioner: alterem/csi-provisioner
  k8s.gcr.io/sig-storage/csi-node-driver-registrar: alterem/csi-node-driver-registrar
  k8s.gcr.io/sig-storage/csi-resizer: alterem/csi-resizer
  k8s.gcr.io/sig-storage/csi-snapshotter: alterem/csi-snapshotter
  k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: alterem/nfs-subdir-external-provisioner
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: alterem/kube-state-metrics
  k8s.gcr.io/prometheus-adapter/prometheus-adapter: alterem/prometheus-adapter
  k8s.gcr.io/metrics-server/metrics-server: alterem/metrics-server
  k8s.gcr.io/ingress-nginx/controller: alterem/ingress-nginx-controller
  k8s.gcr.io/git-sync/git-sync: alterem/git-sync  
  k8s.gcr.io/kube-apiserver: alterem/kube-apiserver
  k8s.gcr.io/kube-controller-manager: alterem/kube-controller-manager
  k8s.gcr.io/kube-scheduler: alterem/kube-scheduler
  k8s.gcr.io/kube-proxy: alterem/kube-proxy
  k8s.gcr.io/pause: alterem/pause
  k8s.gcr.io/etcd: alterem/etcd
  coredns/coredns: alterem/coredns
